### ISSUE TITLE
Allow users to create additional options

### ISSUE THREAD

**Issue by hanzei** [matterpoll/matterpoll#111]
#### Summary

We should allow users to create additional options in addition to the ones defined at the creation of the poll. There should be a Poll Setting for this. I didn't came up with a good name jet, maybe something like `--additional-options`. With this setting selected a new button "Add Option" would show on the left of "Delete Poll", after the options. This opens an interactive message dialogue where the user enters the option text.

#### Describe alternatives you've considered

1. We might allow this by default and add a setting to disable it.
2. Just allow the poll creator to add new options.

#### Additional context

See https://mattermost.atlassian.net/browse/MM-12790 for more infos about Interactive message dialogues.

**Comment by hanzei** [comment]
@kaakaa What do you think about this?

**Comment by kaakaa** [comment]
@hanzei 
Allowing users to add (and delete?) options sounds good feature.

Using interactive message dialog is good, that feature is interesting. (I haven't caught up specs yet)
I supposed that in the future, we can use interactive dialog for editing poll title and re-setting poll settings.
As first step for introducing interactive dialog, implementing additional options sounds good. 
However, do you have anything about deleting options in mind? Like addition, I think that deletion is also necessary, but I don't come up with how to realize it.

We should avoid to add "Add Option" button, because poll post has already had many buttons.
I think that we should start thinking about adding interactive menu for control menu.　Or changing styles of buttons.

> 1. We might allow this by default and add a setting to disable it.

I prefer this.
Because in case of default off, even if users realize that they didn't turn that option on after starting poll, they can not do anything.

> 2. Just allow the poll creator to add new options.

Sounds good 👍 


Any comments?

**Comment by hanzei** [comment]
>  Allowing users to add (and delete?) options sounds good feature.

Deleting options is a neat idea, but the UX is much harder in this case. (Do we inform voter of a deleted option?)
> I supposed that in the future, we can use interactive dialog for editing poll title and re-setting poll settings.
As first step for introducing interactive dialog, implementing additional options sounds good.
However, do you have anything about deleting options in mind? Like addition, I think that deletion is also necessary, but I don't come up with how to realize it.

We could open a dialog with the existing options and let the user erase the one he/she wants to delete.

> We should avoid to add "Add Option" button, because poll post has already had many buttons.
I think that we should start thinking about adding interactive menu for control menu. Or changing styles of buttons.

I agree that a poll has many buttons. Using an interactive menu is a good idea. But I would like to keep this change separate from this feature. I propose to add it as a button for now and change it before the next release.

> I prefer this.
Because in case of default off, even if users realize that they didn't turn that option on after starting poll, they can not do anything.

:+1: 

What Poll Setting name do you prefer?

**Comment by hanzei** [comment]
I'v created a prototype of this feature. The code can be found at the [`111_additional_options`](https://github.com/matterpoll/matterpoll/commits/111_additional_options)  branch.
![matterpoll](https://user-images.githubusercontent.com/16541325/49026397-125cd280-f19e-11e8-851f-300f0306f620.gif)

**Comment by kaakaa** [comment]
> Deleting options is a neat idea, but the UX is much harder in this case. (Do we inform voter of a deleted option?)

It's just an idea, but we can inform voter by creating reply post with mentions.

> We could open a dialog with the existing options and let the user erase the one he/she wants to delete.

I came up with same idea. But I'm not sure that this interaction is good for users.
Since deleting options is not concrete idea now, let's think separately from this issue. Sorry for confusing.

> I agree that a poll has many buttons. Using an interactive menu is a good idea. But I would like to keep this change separate from this feature. I propose to add it as a button for now and change it before the next release.

Agreed.

> What Poll Setting name do you prefer?

* `--no-additional`
* `--disable-additional`

How about?

**Comment by hanzei** [comment]
I think we have different conceptions about the Poll Setting. I had the following in mind:
- By default, we should a "Add Vote". Only the creator and admins can open a dialog by clicking on them. Other people get an error message.
- If the creator provides a Poll Setting X **all** users can add options.

Is is what you also had in mind? If you are fine with this, how do we name X?

**Comment by kaakaa** [comment]
Oh, sorry. I misunderstood and I'm fine with your thought.
Candidates of Poll Settings **X++ are the followings.

* --everyone-add
* --anyone-add
* --public-add
* --add-for-all

I like `--add-for-all`, because I can type easily. But others are fine too.


And @mike_gamble's opinions about positions of buttons and "Edit Poll Options" sounds good.
https://pre-release.mattermost.com/core/pl/5p17es6k8frnbgr3szeugwmm8w

We should tackle additional UI/UX improvement after resolving this and #28.

**Comment by hanzei** [comment]
I went with `public-add-option`.

**Comment by biva** [comment]
Hello! This feature looks great :) When do you plan to release the next version including it?
Thanks!

**Comment by hanzei** [comment]
Hey @biva,

I'm expecting to release a version this month.

Thanks for the interest in Matterpoll!
