### ISSUE TITLE
translations / localizations

### ISSUE THREAD

**Issue by silberzwiebel** [matterpoll/matterpoll#119]
I'd love to see this plugin in non-English languages. Happy to provide a German translation but unsure how and if it's possible at all right now. The best way might be if the plugin uses mattermost's language setting.

**Comment by hanzei** [comment]
This is a huge feature request. Not because of the code changes, these are minor in comparison to the organisational stuff needed for this:

#### Where do we get the translation files from?
It will be a lot of traffic if contributors submit them via a PR. If we fetch them via a external service, we have to set this up.

#### How to we deal with unfinished translations?
Do we just show the english text instead?

#### How do we do QA on the translation?
No idea

### And there are some design questions:
#### What translation to do we use for a poll?
1. Fetch the user setting and use them: This will be a lot of work and there are some parts of the code, where we can't do this, e.g. Slash Commands
2. Use the default language of the server
3. Add a plugin setting for this.
4. A mixture of these

#### Do we choose the language for ephemeral posts in a different way?
There its quite easy to comply with the users personal setting. Is it okay if the language is different from e.g. the one for the buttons.

You see there are a lot of open question. This is definite something I want to do, but it will take time.
