### ISSUE TITLE
Delete Poll / End Poll button should not be accessible to everyone

### ISSUE THREAD

**Issue by LongChair** [matterpoll/matterpoll#289]
#### Summary
Delete Poll / End Poll button should not be accessible to everyone
#### Steps to reproduce
1. start a poll with `/poll "q" "a" "b"`
2. the following popup shows up for **ALL** users
![image](https://user-images.githubusercontent.com/2814651/79439668-6788c680-7fd5-11ea-9e24-7d62e1502c34.png)

I wouldn't want the users to be able to Delete or End the Poll

#### Expected behavior
These buttons should be only accessible to creator and or administror in mattermost

#### Observed behavior (that appears unintentional)
Anyone that sees the poll can delete or end the poll

#### Server configuration
**Operating system:**
Linux

**Mattermost version:**
5.2.0

**Matterpoll version:**
1.3.0

**Updated from an older Matterpoll version or fresh install:**
Fresh install

**Comment by globalqss** [comment]
From my tests the buttons are shown, but they are disabled, wondering why to show a UI component that is useless.

**Comment by kaakaa** [comment]
Thanks @LongChair and @globalqss. I totally agree with your thoughts.

> wondering why to show a UI component that is useless.

Technically, in order to change the look of the poll for each user, we must implement the plugin of `webapp` side, and we didn't have the code for webapp. But I've started to work for UI improvements, and some part of this has been completed by #234. I'm also starting to work on the remaining `Add Option`.

You will be able to use this feature as [Experimental UI](https://github.com/matterpoll/matterpoll#settings) soon, but unfortunately we couldn't cut the release including this improvements. We'll work for that.

**Comment by hanzei** [comment]
https://github.com/matterpoll/matterpoll/pull/234 does fix this issue by hiding the buttons when `Experimental UI ` is enabled
