### ISSUE TITLE
Jest poll_metadata.test.js false positive

### ISSUE THREAD

**Issue by jbattistispiria** [matterpoll/matterpoll#429]
#### Summary
I try to run the jest poll_metadata.test.js with latest version of npm and node but there where falling locally but not in CircleCI.
I look in the CircleCI and they past as a warning because of old version node:
![image](https://user-images.githubusercontent.com/103535117/169550310-28cc9df0-a59f-4112-b7e5-0de2c760fdb8.png)

Not sure if poll_metadata.test.js are false positive?

#### Steps to reproduce
Install latest npm and node to run the tests as failling.

**Comment by kaakaa** [comment]
Thanks for reporting @jbattistispiria. As you reported, `poll_metadata.test.js` doesn't seem to be able to test anything, and seems to result in fail on Node 15 or later. Do you have any idea to test `poll_metadata.js`?

---

Side notes, I'm developing this project on Node 14.16 in order to fit CI environment. It's because this project is following [starter template](https://github.com/mattermost/mattermost-plugin-starter-template) and starter template is using Node 14.16 on CI. AFAIK, the work to update CI environment is in progress in [here](https://github.com/mattermost/mattermost-plugin-starter-template/pull/163#issuecomment-1097523442), but not yet completed.

**Comment by jbattistispiria** [comment]
I won't look at the failing test at the moment.
