### ISSUE TITLE
option invisible after voting

### ISSUE THREAD

**Issue by HedvigS** [matterpoll/matterpoll#452]
#### Summary
Once I've voted in a poll with --progress option on, the option that I've voted for the font goes white. See screenshot below

<img width="1072" alt="Screenshot 2022-09-20 at 16 58 34" src="https://user-images.githubusercontent.com/5327845/191188923-9f6b2231-829d-4d7a-acfa-020faebd6f74.png">

#### Steps to reproduce
1. make a poll with --progress
2. vote yourself
3. try to see all options in the existing poll
 
#### Expected behavior
That all options are readable and not in white font.

#### Observed behavior (that appears unintentional)
The option I've voted for has white font, unless I hover over it.

#### Server configuration
**Operating system:**
Mac oS

**Mattermost version:**
Sorry, don't know. I'm not sys admin for this application for our workspaces

**Matterpoll version:**
Sorry, don't know. I'm not sys admin for this application for our workspaces

**Comment by kaakaa** [comment]
Thanks for reporting @HedvigS . This seems to be same as #402, and it would be fixed in Matterpoll v1.5.0. You can check your Materpoll version from `${SITE_URL}/plugins/com.github.matterpoll.matterpoll/` (e.g.: `https://mattermost.example.com/plugins/com.github.matterpoll.matterpoll/`).

Since Matterpoll v1.5.0 have already been [released](https://github.com/matterpoll/matterpoll/releases/tag/v1.5.0), your administrator can upgrade Matterpoll by manually. However, v1.5.0 haven’t been released to Marketplace, so if your administrator like to manage plugins by marketplace, please track #413.

I’ll close this issue due to duplication, but if you have any other concerns, feel free to reopen this.
