### ISSUE TITLE
Latex with Matterpoll crashes web interfave

### ISSUE THREAD

**Issue by friciwolf** [matterpoll/matterpoll#469]
#### Summary
Matterpoll crashes net interface upon rendering.

#### Steps to reproduce
Steps to reproduce the behaviour:
I wanted to create a poll and used latex rendering which made the web-interface crash. The exact code was the following:
```
/poll "Sind Wirkungsquerschnitte Lorentz-Invariant (LI)? Als Grundlage: $\mathcal{M}$ und der Phasenraum (über den man integriert) ist LI." "Ja, weil die in σ einfließenden Viererimpulse, 'nakten' Teilchengeschwindigkeiten und Energien sich Lorentz-invariant kombinieren lassen." "Per Konstruktion nicht, aber entlang der Beamachse für collider experiments schon (so wie die Pseudorapidität)." "Nein, weil sie geometrische Größen sind, und als solche der Längenkontraktion ausgesetzt." "Nur Mittwochs zwischen 8:00 und 8:05, aber nur wenn die Verwaltung auch besetzt ist." --anonymous --public-add-option
``` 
Supposedly, the latex-syntax is triggering the problem. Interestingly, the android app is capable of dealing with the poll.

**Comment by kaakaa** [comment]
Thank you for reporting. This seems to be caused by Matterpoll's **Experimental UI** settings, and we need to fix webapp code to support inline latex text. If you need to fix this soon, disabling **Experimental UI** setting should fix this issue.

>  Interestingly, the android app is capable of dealing with the poll.

Since Mattermost mobile app doesn't support every plugin features, mobile app would not be affected by this issue.
https://github.com/mattermost/mattermost-mobile/issues/3883#issuecomment-1148519369

**Comment by friciwolf** [comment]
Hi @kaakaa ,
thanks a lot for your prompt and kind reply; I am forwarding this piece of information to our admins.
The issue could have been temporarily solved by removing the post from the database, but that only fixed it for now.

I'll keep the ticket open such that it remains in sight.

**Comment by friciwolf** [comment]
Hey @kaakaa !
Thanks you very for fixing this issue! I think most physicists and mathematicians using matterpoll have just received a great quality-of-life-improving update ;)
