### ISSUE TITLE
Multi answer option

### ISSUE THREAD

**Issue by kaakaa** [matterpoll/matterpoll#84]
Now, users can vote just one answer.
It had better to add settings that users can vote multi answers.

**Comment by kaakaa** [comment]
Yes, you are right. I'll work on #28 first. Leave this as backlog.

> This will most likely require a migration of existing polls to a new schema.

Is it sure? I don't think that we need to migrate existing poll data.
We can handle poll with multi setting.

```
{
  Poll: {
    Question: "Is this Matterpoll great?",
    AnswerOptions: [
      {
        Answer: "Of course",
        Vote: ["User1", "User2"]
      },
      {
        Answer: "In any case",
        Vote: ["User1", "User2"]
      },
      {
        Answer: "Definitely",
        Vote: ["User1", "User2"]
      }
    ]
  }
}
```

Of course, `Multi` field will be added to `PollSetting`, but it should not be necessary for migration.

**Comment by hanzei** [comment]
I would assume`Multi` is an integer, which indicates the the number of votes a user has. But an integer has a default value of 0. Because of this we have to iterate over every existing poll and set `Multi` to 1.

**Comment by cpanato** [comment]
can make a flag when creating the poll? in some cases the user might want just one answer but in other cases they want multiple answers

**Comment by hanzei** [comment]
If anyone wants to work on this, please let me know!

**Comment by hanzei** [comment]
The current design proposal is:

There should be a new Poll Setting `votes`. It should be used like this `votes=X` and would accept any integer > 1 for `X`. Otherwise an error is thrown when creating the poll.

Only if this setting is set for a poll, there is an additional button "Reset Votes" that when pressed resets all cast votes for the user.


The behaviour when pressing option buttons should be if e.g. every user has 2 votes:
- When clicking on the first option, send an ephemeral message: "Your vote has been counted. You have 1 vote left."
- When clicking on the second option, send an ephemeral message: "Your vote has been counted. You have 0 votes left."
- When clicking on a already selected option, send an ephemeral message: "Your already voted for this option."
- When clicking on the section option,  send an ephemeral message: "You can't vote, because you don't have any votes left. Use the reset button to reset your votes."

Feedback on this proposal is welcome!

**Comment by robert-mraz** [comment]
Would be also nice, if user can withdraw the particular vote.

**Comment by hanzei** [comment]
@robert-mraz You mean like in the current implementation? It problem is, that the user might not know, what he/she voted for.

How exactly should this case be handelt in your mind?

**Comment by SCrocky** [comment]
@hanzei The user would know what he voted for because it would be highlighted, no?

**Comment by hanzei** [comment]
The highlighting is part of the Experimental UI and not enabled by default.

**Comment by kaakaa** [comment]
I'll take this issue and implement according to[hanzei's comment](https://github.com/matterpoll/matterpoll/issues/84#issuecomment-543342123).

**Comment by kadafax** [comment]
just a friendly bump, any news on this ?

**Comment by kaakaa** [comment]
@kadafax Thanks for your comments. We work on #256. Please wait a moment.
