### ISSUE TITLE
Use packages

### ISSUE THREAD

**Issue by hanzei** [matterpoll/matterpoll#86]
Currently we store every file into  `server/` in package `main`. I would like to split these files into multiple packages:
- `main`: Just contains `main.go`
- `plugin`: Contains every hock
- `utils`: Self explaining
- `model?`:  contains `poll.go`. I'm not sure with the name. Its a fine name but duplicate  with `mattermost/mattermost-server/model`. But I don't want to name it `poll` to leave room for more.

**Comment by hanzei** [comment]
While starting to work on this I encountered an issue:
We currently store test data in `plugin_test.go`. When splitting up the code into multiple packages, this data is not available for other packages. And because of cycle imports, it not possible to just import it.

My current workaround is, to just copy the data and have it in multiple packages. Which is fine but not great.

**Comment by kaakaa** [comment]
Creating `model` package is fine.
Other idea is `store` or `data` package, because `poll.go` represents data to be stored. It's not natural, but fine too.

About spliting test data.
I want to avoid distributing different variables of the same name among multiple packages. So we can create `utils/testutils` package lilke mattermost-server.
https://github.com/mattermost/mattermost-server/blob/4e59a27293394b6d5529efd13ad711daebbc0eb3/app/apptestlib.go#L39

How does it sounds?

**Comment by hanzei** [comment]
> I want to avoid distributing different variables of the same name among multiple packages. So we can create utils/testutils package lilke mattermost-server.

Great idea! :+1: 

> Creating model package is fine.
Other idea is store or data package, because poll.go represents data to be stored. It's not natural, but fine too.

If we name the package model, how would you name `github.com/mattermost/mattermost-server/model`?
